---
- name: Ensure redis server is installed.
  yum:
    name: redis
    enablerepo: epel
    state: installed

- name: Copy a redis config file.
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
  notify:
    - restart redis

- name: Ensure redis is started and enabled to start at boot.
  service: name=redis state=started enabled=yes
