---
- name: Ensure redis server is installed.
  yum:
    name: redis
    enablerepo: epel
    state: installed

- name: Ensure redis is started and enabled to start at boot.
  service: name=redis state=started enabled=yes
